/*
 * (C) Frank Migliorino 2014
 * CSE 219 Final Project
 * Portions Copyright Paul Fodor
 */
package jte;

/**
 *
 * @author Frank
 */
public enum JTEPropertyType {
    UI_PROPERTIES_FILE_NAME, PROPERTIES_SCHEMA_FILE_NAME,DATA_PATH,
    RESOURCE_LOCATION, 
    
    HELP_FILE,
    
    //XML
    XML_CITIESSCH,XML_CITIESFILELOC,
    XML_CITIESROOT, XML_CITYNODE, XML_CITYNAME, XML_CITYCOLOR, XML_CITYX, XML_CITYY,
    XML_CITYID, XML_CITYDESC, XML_CITYFLIGHTLOC, XML_CITYFLIGHTLOCX, XML_CITYFLIGHTLOCY,
    
    XML_RTROOT, XML_RTCITY, XML_RTID, XML_RTLAND, XML_RTSEA,
    //End XML
    
    UI_RADIUS, NUM_CARDS,
    
    noothing;
}
